[package]
name = "helper-oxide"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0.188"
futures = "0.3.28"
tokio = {version = "1.32.0", features = ["full"]}
indicatif = "0.17.8"
rayon = "1.10"
serde_json = "1.0.128"

[dependencies.mongodb]
version = "3.1.0"
features = ["sync"]
